// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlxe2dvu1luD06pTOsMVpvoWjSVpcO3e4',
    appId: '1:332896765037:web:0b33285122e5ae516b6b64',
    messagingSenderId: '332896765037',
    projectId: 'druvtech8',
    authDomain: 'druvtech8.firebaseapp.com',
    storageBucket: 'druvtech8.appspot.com',
    measurementId: 'G-1YN0RR93NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAatZPYqM8kOEHcQgRehPXQl4E3h3Cm1EQ',
    appId: '1:332896765037:android:2a368888551da4886b6b64',
    messagingSenderId: '332896765037',
    projectId: 'druvtech8',
    storageBucket: 'druvtech8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC0eKOnmrVgCptszIrRT6dQWaDi2NVMPo',
    appId: '1:332896765037:ios:b515bb45951084ba6b6b64',
    messagingSenderId: '332896765037',
    projectId: 'druvtech8',
    storageBucket: 'druvtech8.appspot.com',
    androidClientId: '332896765037-50ug4b76nkl534eol6aa3gibnnuupo2u.apps.googleusercontent.com',
    iosClientId: '332896765037-0gsqit82bs840167kf5cq1cc0k1s0blm.apps.googleusercontent.com',
    iosBundleId: 'com.example.druvtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC0eKOnmrVgCptszIrRT6dQWaDi2NVMPo',
    appId: '1:332896765037:ios:b515bb45951084ba6b6b64',
    messagingSenderId: '332896765037',
    projectId: 'druvtech8',
    storageBucket: 'druvtech8.appspot.com',
    androidClientId: '332896765037-50ug4b76nkl534eol6aa3gibnnuupo2u.apps.googleusercontent.com',
    iosClientId: '332896765037-0gsqit82bs840167kf5cq1cc0k1s0blm.apps.googleusercontent.com',
    iosBundleId: 'com.example.druvtech',
  );
}
